version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 973816448278.dkr.ecr.us-west-2.amazonaws.com/youtube
  post_build:
    commands:
      - docker push 973816448278.dkr.ecr.us-west-2.amazonaws.com/youtube:latest
      - printf '[{"name":"helloworld","973816448278.dkr.ecr.us-west-2.amazonaws.com/youtube:latest":"%s"}]' 973816448278.dkr.ecr.us-west-2.amazonaws.com/youtube > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
